### ISSUE TITLE
utterances still not working correctly :)

### ISSUE THREAD

**Issue by jschpp** [mczerniawski/mczerniawski.github.io#3]
Thanks a lot:) Fixed and it's working!

_Originally posted by @mczerniawski in https://github.com/mczerniawski/mczerniawski.github.io/issues/2#issuecomment-486141207_

Splitted this issue since it doesn't concern the original post :)

now it's telling me this:
Error: utterances is not installed on mczerniawski/mczerniawski.github.io. If you own this repo, [install the app](https://github.com/apps/utterances). Read more about this change in the [PR](https://github.com/utterance/utterances/pull/25).

**Comment by mczerniawski** [comment]
Somehow I missed your issue:(
I've fixed it now - I'm able to post comments - can you check please?

**Comment by jschpp** [comment]
It seems to be working now :)
